- name: disable default redis and enable redis 7
  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y

- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: update redis config file listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: update redis config file listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'
