- name: include maven.yml
  ansible.builtin.include_role:
    name: common
    tasks_from: maven.yml

-name: install mysql
  ansible.builtin.dnf:
    name: mysql
    state: installed


- name: load schema
  ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/db/schema.sql

- name: load schema
  ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: load schema
  ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/db/master-data.sql

- name: start service
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted