- name: Download foo.conf
  hosts: all
  become: true
  tasks:
    - name: download at remote
      ansible.builtin.get_url:
        url: http://example.com/path/file.conf
        dest: /etc/foo.conf
        mode: '0440'

