- name: Download foo.conf
  hosts: all
  become: true
  tasks:
    - name: download at remote
      ansible.builtin.get_url:
        url: https://httpd.apache.org/docs/current/install.html
        dest: /etc/file.txt
        mode: '0440'



