- name: Run shipping
  include_role:
    name: common
    tasks_from: docker.yml
  vars:
    app_port: 8080

- name: Run a shipping container
  community.docker.docker_container:
    name: "shipping-{{ item }}"
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    recreate: yes
    env_file: /opt/shipping-env
    env:
      SCHEMA_file: "db/app-{{ item }}.sql"
    loop:
      -app-user
      -schema
      -master-data



