- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.include_role:
    name: common
    tasks_from: docker.yml
  vars:
    app_port: 8080

- name: run a schema
  community.docker.docker_container:
    name: "catalogue-schema"
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    recreate: yes
    env_file: /opt/catalogue.env

