- name: include nodejs tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml

- name: copy mongodb repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongosh
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: master data load
  ansible.builtin.shell: mongosh --host MONGODB-SERVER-IPADDRESS </app/db/master-data.js