- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Include task list in play
  ansible.builtin.include_tasks:
      file: artifacts.download.yml

- name: Change the working directory to /app before executing the command
  ansible.builtin.shell: mvn clean package ; mv target/{{ component_name }}-1.0.jar {{ component_name }}.jar
  args:
    chdir: /app

- name: Include task systemd_setup
  ansible.builtin.include_tasks:
      file: systemd.setup.yml.
